exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: "Studio Centauri"
subtitle: "Game Development Society, IIT Kanpur"
url: "http://studiocentauri.github.io" # the base hostname & protocol for your site
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: announcement
    desc: "New projects, updates, events."

  - cat: devlog
    desc: "See how we make this amazing stuff."
